### ISSUE TITLE
怎么使用呢

### ISSUE THREAD

**Issue by hzh747117982** [percent4/llm_math_solver#1]
直接运行math_solver_pipleline.py并没有任何输出呢，不太懂如何使用，可以说明一下吗

**Comment by percent4** [comment]
需要先部署自研微调模型（模型网址： https://huggingface.co/jclian91/Qwen2-72B-Instruct-math），然后结合Open WebUI使用，具体可以参考这篇文章：https://mp.weixin.qq.com/s?__biz=MzU2NTYyMDk5MQ==&mid=2247487013&idx=1&sn=6a6786ba8c8c7cfdbc02ef558adefe71&chksm=fcb9b7b5cbce3ea37f8fb61e743d0ea0a7d4f5d6b8e8b2c7a80171a5c8c217524d8f307c0146&token=120899150&lang=zh_CN#rd
